---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
namespace: pidginhost
name: cloud
version: "0.6.0"
readme: README.md
authors:
  - Popescu Andrei Cristian (@shbpty)
description: PidginHost Ansible Collection
license_file: GPL-3.0
tags:
  - cloud
  - pidginhost
  - server
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
