#List all firewall on your account.

---
- name: List all firewall on your account
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    pidgin_host_token: "{{ lookup('ansible.builtin.env', 'PIDGINHOST_ACCESS_TOKEN') }}"

  tasks:
    - name: Print all firewalls data
      pidginhost.cloud.firewalls_info:
        state: present
        token: "{{ pidgin_host_token }}"
      register: result

    - debug:
        msg: "{{ result }}"