---
# Usage:
#   ansible-playbook -i inventory/pidginhost.yml playbooks/firewalls_info.yml
- name: Retrieve firewall information
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    firewalls_state: present

  tasks:
    - name: Query firewall data
      pidginhost.cloud.firewalls_info:
        state: "{{ firewalls_state }}"
      register: firewalls_result

    - name: Show firewalls
      ansible.builtin.debug:
        var: firewalls_result.firewalls
