---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/firewall.yml -v

- name: Create firewalls rules set, add rules to rules set or delete rules set.
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Delete firewall rules set
      pidginhost.cloud.firewall:
        state: absent
        rules_set_name: Firewall rules set name

    - name: Create firewall rules set
      pidginhost.cloud.firewall:
        state: present
        create_rules_set: true
        rules_set_name: Firewall rules set name

    - name: Add firewall rules to rules set
      pidginhost.cloud.firewall:
        state: present
        rules_set_name: New Firewall1
        create_rules_set: false
        direction: in
        action: ACCEPT
        protocol: tcp
        source: str
        sport: str
        destination: str
        dport: 22
        enabled: true
        position: 0