---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/firewall_action.yml -v

- name: Add public interface to server.
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add public interface
      pidginhost.cloud.firewall_action:
        state: present
        policy_in: ACCEPT
        policy_out: ACCEPT
        server_hostname: hhtest5.com
        rules_set_name: Firewall rules set name