---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/packages_info.yml -v

- name: Get PidginHost Packages info
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Print all server packages data
      pidginhost.cloud.packages_info:
        state: present