#short_description: Get Public Interface information for specific server.

#description:
#  - Get Public Interface information for specific server.

#EXAMPLES
#- name: Print public interface
#  pidginhost.cloud.public_interface_info:
#    state: present
#    server_id: 624
#    token: "{{ pidgin_host_token }}"

---
- name: Print public interface
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    pidgin_host_token: "{{ lookup('ansible.builtin.env', 'PIDGINHOST_ACCESS_TOKEN') }}"

  tasks:
    - name: Print volumes info for specific Server id
      pidginhost.cloud.public_interface_info:
        state: present
        server_id: 707
        token: "{{ pidgin_host_token }}"
      register: result

    - debug:
        msg: "{{ result }}"