---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/public_interface_info.yml -v

- name: Print public interface
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print volumes info for specific Server id
      pidginhost.cloud.public_interface_info:
        state: present
        server_id: 707
      register: result