#short_description: Get specific server ip

#EXAMPLES
#- name: Get specific server ip
# pidginhost.cloud.server_public_ip:
#   token: "{{ token }}"
#   state: present
#   server_hostname: "{{ server_hostname }}"

---
- name: Get specific server ip
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    pidgin_host_token: "{{ lookup('ansible.builtin.env', 'PIDGINHOST_ACCESS_TOKEN') }}"

  tasks:
    - name: Get specific server ip
      pidginhost.cloud.server_public_ip:
        state: present
        token: "{{ pidgin_host_token }}"
        server_hostname: UixUhRmLMCCUdcj
      register: result

    - debug:
        msg: "{{ result }}"