---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/servers_info.yml -v

- name: Print all Servers info
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print all Servers info
      pidginhost.cloud.servers_info:
        state: present