---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/server.yml -v

- name: Create or delete Servers
  hosts: localhost
  tasks:
    - name: Create Server
      pidginhost.cloud.server:
        state: present
        unique_hostname: true
        image: string
        package: string
        hostname: string
        project: string
        password: string
        ssh_pub_key: string
        ssh_pub_key_id: string
        new_ipv4: true
        new_ipv6: true
        public_ip: string
        public_ipv6: string
        fw_rules_set: string
        fw_policy_in: ACCEPT
        fw_policy_out: ACCEPT
        private_network: string
        private_address: 198.51.100.42
        extra_volume_product: string
        extra_volume_size: 0
        no_network_acknowledged: true

    - name: Delete Server by server hostname
      pidginhost.cloud.server:
        state: absent
        unique_hostname: true
        hostname: string

    - name: Delete Server by server id
      pidginhost.cloud.server:
        state: absent
        server_id: true