---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/server_public_ip.yml -v

- name: Get specific server ip
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get specific server ip
      pidginhost.cloud.server_public_ip:
        state: present
        server_hostname: UixUhRmLMCCUdcj