---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/ssh_keys_info.yml -v

- name: Get SSH keys info
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print all SSH keys info
      pidginhost.cloud.ssh_keys_info:
        state: present