---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/ssh_key.yml -v

- name: Handle SSH keys
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    state: present
    delete_others: false
    keys_list:
      - "ssh-ed25519 yrty/2EOZ40JU5paEHP7ejAO7PB ansible"

  tasks:
    - name: Add SSH keys
      pidginhost.cloud.ssh_key:
        state: present
        delete_others: false
        ssh_pub_key: "{{ item }}"
      with_items: "{{ keys_list }}"
      when: not delete_others

    - name: Delete SSH keys
      pidginhost.cloud.ssh_key:
        state: absent
        delete_others: false
        ssh_pub_key: "{{ item }}"
      with_items: "{{ keys_list }}"
      when: not delete_others

    - name: Add specified SSH keys and delete any other SSH keys found based on the delete_others flag
      pidginhost.cloud.ssh_key:
        state: present
        delete_others: true
        ssh_pub_key: "{{ keys_list }}"
      when: delete_others == true and state == 'present'`