---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/volume.yml -v

- name: Create or Delete PidginHost volume
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Delete volume
      pidginhost.cloud.volume:
        state: present
        product: fast-storage
        volume_alias: Volume4444
        hostname: hhtest22332.com
        size_gigabytes: 50

    - name: Add volume to Server
      pidginhost.cloud.volume:
        state: present
        project: "str"
        product: "fast-storage"
        hostname: 23423
        volume_alias: alias
        size_gigabytes: 10