---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost playbooks/volume_action.yml -v

- name: Attach or Detach volume from Server
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Attach volume to Server
      pidginhost.cloud.volume_action:
        state: present
        volume_alias: alias
        server_hostname: hostname.com

    - name: Detach volume from Server
      pidginhost.cloud.volume_action:
        state: absent
        volume_alias: alias
        server_hostname: hostname.com