---
# Usage:
#   ansible-playbook -i inventory/pidginhost.yml playbooks/volumes_products_info.yml
- name: Retrieve volume products
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    volumes_products_state: present

  tasks:
    - name: Query volume products
      pidginhost.cloud.volumes_products_info:
        state: "{{ volumes_products_state }}"
      register: volumes_products_result

    - name: Show volume products
      ansible.builtin.debug:
        var: volumes_products_result.volumes
