#short_description: Print volumes Products info.

---
- name: Get volumes Products info
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    pidgin_host_token: "{{ lookup('ansible.builtin.env', 'PIDGINHOST_ACCESS_TOKEN') }}"

  tasks:
    - name: Print all volumes Products
      pidginhost.cloud.volumes_products_info:
        state: present
        token: "{{ pidgin_host_token }}"
      register: result

    - debug:
        msg: "{{ result }}"